### ISSUE TITLE
questions about the function 'prepare_test_data_semseg( )'

### ISSUE THREAD

**Issue by linhaojia13** [AnTao97/dgcnn.pytorch#1]
Hi, Thank you for your good works. 
I noticed that you in the function 'prepare_test_data_semseg( )', it run the scripts 'prepare_data/collect_indoor3d_data.py' and 'prepare_data/gen_indoor3d_h5.py' to transform the raw dataset 'Stanford3dDataset_v1.2_Aligned_Version' to 'indoor3d_sem_seg_hdf5_data_test'.
However, as descripted in the pointnet repo https://github.com/charlesq34/pointnet/tree/master/sem_seg#dataset, the two scripts will transforms the raw data to the training dataset which is sampled 4096 points in each block and is not suitable for testing which requires the all points but not the sampled ones.

**Comment by antao97** [comment]
Actually, if you look into the code in [charlesq34/pointnet/sem_seg](https://github.com/charlesq34/pointnet/tree/master/sem_seg) carefully, you will find charlesq34 does sample 4096 points in each block (1m x 1m x height of the room) to test the network. The main difference between training and testing set is that each block in training set overlaps with its neighbor blocks in 0.5m, i.e. all blocks in a given room are cropped with stride=0.5m, while all blocks in testing set are not overlap with others.

**Comment by linhaojia13** [comment]
Thank your for your prompt reply.
I agreed with your opinions about the difference between the training and testing dataset after I look into the scripts 'gen_indoor3d_h5.py' and 'batch_inference.py'.
Do you think this means that Charlesq34 disobey the promise that he made in the paper which says 'At test time, we test on all the points' ?

**Comment by antao97** [comment]
It's a good question haha😁 and I suggest you ask Charlesq34 to confirm.
In my opinion, Charlesq34's original intention is to test his model on all points in testing set to meet the testing standard. But as you know the model is trained with 4096 points per block so it may not work well with arbitrary number of input points. 
You can also find that points of each shape in testing set are sampled under fixed number in classification and part segmentation task. It's a common choice to sample fixed number of points per shape to test model.

**Comment by linhaojia13** [comment]
Hhhh thank you. I would share my opinions with you once I got new understanding about this issue.
