### ISSUE TITLE
For part_seg, how can I directly train the full dataset but just test on one class choice?

### ISSUE THREAD

**Issue by mutianxu** [AnTao97/dgcnn.pytorch#10]
Dear author,

How can I directly train the full dataset, then use this trained model to test on one class choice?

**Comment by antao97** [comment]
The part segments of different classes are aranged in an order. 

https://github.com/AnTao97/dgcnn.pytorch/blob/8c28fad1ce08ef91371d3fff72eeccb63a259099/data.py#L207-L211

`self.cat2id` is the dictionary between classes‘ name and id. `self.seg_num` represents the number of segments in each class, while `self.index_start` represents the starting indexs of all classes in the output 50-dim vector. 

If you want to evaluate performance in a particular class with full dataset trained, the only thing you need to do is to calculate Acc and mIoU in some chosen dims of the 50-dim vector.
