### ISSUE TITLE
The returned feature after knn is not contiguous, slowing down the forward process tremendously.

### ISSUE THREAD

**Issue by kentechx** [AnTao97/dgcnn.pytorch#12]
This code
https://github.com/AnTao97/dgcnn.pytorch/blob/8d287d92479a79fc6ff5f70b5ad7eacbf3ecdd38/model.py#L60
should be modified as 
```
 feature = torch.cat((feature-x, x), dim=3).permute(0, 3, 1, 2).contiguous()
```
Use this simple code to test the forwarding speed during training.
```
import torch
from model import DGCNN_partseg
from tqdm import tqdm

class A:pass
args = A
args.k = 16
args.emb_dims = 1024
args.dropout = 0.5

model = DGCNN_partseg(args, 10).cuda()
x = torch.randn((8, 3, 2048)).cuda()
l = torch.zeros((8, 16, 1)).cuda()

model.train()
for i in tqdm(range(1000)):
    out = model(x, l)
```

Following are the speed results in my computer( RTX 2080Ti):
1) not contiguous
> 100%|██████████| 1000/1000 [02:39<00:00,  6.27it/s]
2) continuous
> 100%|██████████| 1000/1000 [00:46<00:00, 21.44it/s]

**Comment by antao97** [comment]
Thanks for your feedback!

I have modified it in the updated code.
