### ISSUE TITLE
About the transform_net

### ISSUE THREAD

**Issue by Yellowshuohahaha** [AnTao97/dgcnn.pytorch#14]
Thanks for your great work of pytorch implement of DGCNN! I want to ask why the cls and semseg model haven't the transform_net but the partseg model add it? The tansform_net can affect  accuracy of the result?

**Comment by antao97** [comment]
Sorry I don't know. I just follow what the original implementation did and write it in PyTorch.

**Comment by Yellowshuohahaha** [comment]
I see the issue of author's code and find the tansform_net does't affect the result. Thans for your code again!
