### ISSUE TITLE
Any difference between your implementation and official version on classification task?

### ISSUE THREAD

**Issue by usherbob** [AnTao97/dgcnn.pytorch#15]
Hello, 

It seems the pretrained weights you released better than the official version. Since your DGCNN_cls implementation is same as [the official version](https://github.com/WangYueFt/dgcnn/blob/master/pytorch/model.py), I wonder if there is any difference between your training conditions and the official version(i.e. data augmentation, epochs)?

Best regards.

**Comment by antao97** [comment]
No difference.

I just re-run the code for several times, and get better results.
