### ISSUE TITLE
Problem in the training of seg

### ISSUE THREAD

**Issue by AmosYelo** [AnTao97/dgcnn.pytorch#16]
In the part of seg , I've got the dataset ready ,but when i run the code ,there is still something wrong.
 How can i solve it ,thank you
![image](https://user-images.githubusercontent.com/59718396/96403298-955ff980-120a-11eb-9978-859c9e1b3aac.png)

**Comment by antao97** [comment]
I think there is something wrong with your dataset path. Please make sure your dataset is in `/data`.

**Comment by AmosYelo** [comment]
Thanks,
