### ISSUE TITLE
Problem when train the semseg script

### ISSUE THREAD

**Issue by 964918993** [AnTao97/dgcnn.pytorch#17]
Sorry to bother you, but I have one question when  I train the semseg script.

I have downloaded 2 datasets and unzipped them in 'data', then I have 'indoor3d_sem_seg_hdf5_data' and 'stanford_indoor3d'. However, when I run the script 'main_semseg.py', it shows 'ValueError: need at least one array to concatenate'.

Did I lost some steps? Coule you give me your help? Thanks.

**Comment by antao97** [comment]
I think you don't place zip file `Stanford3dDataset_v1.2_Aligned_Version.zip` properly under `data/`.

**Comment by 964918993** [comment]
I remember that I put the zip file 'Stanford3dDataset_v1.2_Aligned_Version.zip'under data/, and when I run 'main_semseg.py', the zip file is deleted and unzipped into the same root as data/. Then I copied the unzipped file and the zip file under data/. It did not work.

**Comment by antao97** [comment]
So can you paste all error output here?

**Comment by 964918993** [comment]
Thanks for your reply. As the computer is currently unavailable, I will paste it up a few days later.

**Comment by 964918993** [comment]
I ran the main_semseg.py successfully, thanks.

**Comment by howtoknowseg** [comment]
Excuse me, I have the same question when training the semseg script, could you tell me how you solve it?

**Comment by shayannikoohemat** [comment]
If the unzipped file `Stanford3dDataset_v1.2_Aligned_Version` is not under data/ then copy it to `data` directory and run the code again, it solved my problem. Make sure the file name is exactly the same as here because this is the name the script is looking for.
