### ISSUE TITLE
About Part Seg

### ISSUE THREAD

**Issue by ChenhLiwnl** [AnTao97/dgcnn.pytorch#19]
Hello!
I want to ask that how many epoches it took to get the best mIoU(85.2%) when you trained the model?
Also I noticed that this line ( line 117 )
            seg = seg - seg_start_index
I don't understand the usage of this line, could you please explain?

**Comment by antao97** [comment]
See #10 and #20.

**Comment by ChenhLiwnl** [comment]
Thank you
