### ISSUE TITLE
 Test results.

### ISSUE THREAD

**Issue by 964918993** [AnTao97/dgcnn.pytorch#21]
Have you ever wondered why your code implement is higher than the original paper? Is there any changes on net structure or used some tricks?

**Comment by 964918993** [comment]
I see you say that the classification task is run multiple times with good results, but is the same for part segmentation and semantic segmentation? Just run many times?

**Comment by antao97** [comment]
> I see you say that the classification task is run multiple times with good results, but is the same for part segmentation and semantic segmentation? Just run many times?

I did run multiple times for part segmentation task. 
For semantic segmentation, I only run the exp in one time.

Except for runing the exp multiple times, there are no other changes or tricks.

**Comment by 964918993** [comment]
Thanks for your reply.
