### ISSUE TITLE
Results on part segmentation

### ISSUE THREAD

**Issue by edshkim98** [AnTao97/dgcnn.pytorch#25]
Hi, I have another question to ask you.
I am currently using your part seg model, but doesn't seem to get the iou stated on the paper.
However, you have said in the other posts that you have re-run the same exp for multiple times, is it correct?
Why does it make the model to perform better and what is the difference between increasing epochs and re-run the same experiment for multiple times?
Also, how many times have you re-run the experiment to get the values on the paper?
Thank you.

**Comment by edshkim98** [comment]
Sorry I have another question regarding the number of k for knn.
In the paper, it says k=20 for 1024 points and k=40 for 2048 points.
Does this mean if I have point cloud larger than 2048 pts e.g.8192 points, then do I have to choose k = 160 for the best outcome?

**Comment by antao97** [comment]
I suggest you re-run the exp because the optimizer has randomness. For point cloud exp, the randomness is usually big.

In the DGCNN paper, the author only runs the exp on the two settings (k=20 for 1024 points and k=40 for 2048 points).
