### ISSUE TITLE
Part Segmentation visualization

### ISSUE THREAD

**Issue by fdshan** [AnTao97/dgcnn.pytorch#26]
Hi,
I have already go through all steps in part segmentation and I want to visualize the final results. I saw you post a really detail explanation at issue8 about how to visualize the final results. But I can not figure out where is the output file that I can know which points are from the same class. Could you please explain about how to store the class information? Sorry for ask such a silly question, I'm a beginner for this and this question actually bother me for few days : )
Thank you so much!

**Comment by antao97** [comment]
https://github.com/AnTao97/dgcnn.pytorch/blob/843abe82dd731eb51a4b3f70632c2ed3c60560e9/main_partseg.py#L240
Point clouds are processed with a batch size N=16 in `test_loader`. `data` represents point cloud data (size Nx2048x3). `label` represents ground-truth class label (size N) (see line 207-209 in `data.py`). `seg` represents ground-truth segment label (size Nx2048) (see line 210-211 in `data.py` and issue #10).

https://github.com/AnTao97/dgcnn.pytorch/blob/843abe82dd731eb51a4b3f70632c2ed3c60560e9/main_partseg.py#L252-L253
`seg_np` represents ground-truth segment label in numpy array (size Nx2048). `pred_np` represents predicted segment label in numpy array (size Nx2048).

If you want to output a single point cloud shape with predicted segment labels, select one point cloud shape in `data` and output corresponding segment labels in `pred_np`.

**Comment by fdshan** [comment]
Thank you so much!!!

**Comment by antao97** [comment]
The visualization code is added in this repo.
