### ISSUE TITLE
S3DIS training Error

### ISSUE THREAD

**Issue by edshkim98** [AnTao97/dgcnn.pytorch#28]
Hi, I am trying to run training a model on S3DIS dataset using your code.
I think I've followed correct steps which are to download the Aligned version from the link and download another dataset
from https://github.com/charlesq34/pointnet/blob/master/sem_seg/download_data.sh, all under /data folder.
However, when I run the code, it gives the following error and I am not sure how to fix it.

Traceback (most recent call last):
  File "main_semseg.py", line 318, in <module>
    test(args, io)
  File "main_semseg.py", line 192, in test
    test_loader = DataLoader(S3DIS(partition='test', num_points=args.num_points, test_area=test_area),
  File "/home/ubuntu/shkim/dgcnn.pytorch/data.py", line 246, in __init__
    self.data, self.seg = load_data_semseg(partition, test_area)
  File "/home/ubuntu/shkim/dgcnn.pytorch/data.py", line 147, in load_data_semseg
    data_batches = np.concatenate(data_batchlist, 0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate

Could you please give me an advice how to fix this issue? Thank you!

**Comment by antao97** [comment]
It seems that your downloaded dataset is not placed correctly.

**Comment by edshkim98** [comment]
@AnTao97 Hi thank you for the reply.
Could you please elaborate a little bit more of how to prepare dataset? I have created a folder called ‘data’ under the cloned repository and then placed the Aligned Version.zip file inside the data. Have I missed something?

**Comment by antao97** [comment]
Do you get `/data/indoor3d_sem_seg_hdf5_data` and `/data/indoor3d_sem_seg_hdf5_data` folder correctly?

If you don't know how to do, please remove anything under `/data` except `Stanford3dDataset_v1.2_Aligned_Version.zip` and then rerun the code.

**Comment by edshkim98** [comment]
@AnTao97 , Thank you for the quick reply.
I've re-downloaded Aligned_Version.zip and tried again but got following error message (3 errors).

```
Traceback (most recent call last):
  File "prepare_data/collect_indoor3d_data.py", line 29, in <module>
    indoor3d_util.collect_point_label(anno_path, os.path.join(output_folder, out_filename), 'numpy')
  File "/home/ubuntu/shkim/dgcnn.pytorch/prepare_data/indoor3d_util.py", line 60, in collect_point_label
    data_label = np.concatenate(points_list, 0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
/home/ubuntu/shkim/dgcnn.pytorch/data/stanford_indoor3d/Area_1_conferenceRoom_1.npy
Traceback (most recent call last):
  File "prepare_data/gen_indoor3d_h5.py", line 79, in <module>
    random_sample=False, sample_num=None)
  File "/home/ubuntu/shkim/dgcnn.pytorch/prepare_data/indoor3d_util.py", line 259, in room2blocks_wrapper_normalized
    data_label = np.load(data_label_filename)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/shkim/dgcnn.pytorch/data/stanford_indoor3d/Area_1_conferenceRoom_1.npy'
Please download Stanford3dDataset_v1.2_Aligned_Version.zip                 from https://goo.gl/forms/4SoGp4KtH1jfRqEj2 andplace it under data/
```

It seems to create /data/indoor3d_sem_seg_hdf5_data and indoor3d_sem_seg_hdf5_data_test.
Also, it creates an empty stanford_indoor3d folder inside data which I think it is related to the above error.
Do you have any idea how to solve this issue?

**Comment by antao97** [comment]
Try to rename `Aligned_Version.zip` into `Stanford3dDataset_v1.2_Aligned_Version.zip`?

Please read the code in `data.py` carefully. Then, you will know how data is processed.
