### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by ycjing** [AnTao97/dgcnn.pytorch#30]
Hi @AnTao97 

Thank you for the great work! I wonder what the training time on the task of part segmentation with the default setting (4 GPUs, batch size is 32), for the full dataset and with class choice? I really appreciate your help! Thank you! 

Best,
Yongcheng

**Comment by antao97** [comment]
I'm sorry I forgot the exact training time. But I can be sure that the training time is less than one day.

**Comment by ycjing** [comment]
Hi @AnTao97 

Thank you for the quick response! I truly appreciate it.

Best,
Yongcheng
