### ISSUE TITLE
Visualizing Feature Map

### ISSUE THREAD

**Issue by edshkim98** [AnTao97/dgcnn.pytorch#31]
Hello again, the original DGCNN paper was able to show the feature map as below. 
Do you know how to construct and visualize the feature map like this?
I would like to visualize feature map for each edgeconv layer.
Thank you.

![image](https://user-images.githubusercontent.com/32335758/109505282-c7019f00-7adf-11eb-83d8-819a8d328db0.png)

**Comment by antao97** [comment]
I think the feature map is generated by calculating the feature distances between a given point (depicted as the red point) and the rest of the points.

For more details, I think you should ask the author of DGCNN for help.
