### ISSUE TITLE
Problems with semseg 

### ISSUE THREAD

**Issue by howtoknowseg** [AnTao97/dgcnn.pytorch#33]
Excuse me,I have printed the data_batchlist and the label_batchlist and they are not empty,but it still outputs the error: ValueError: need at least one array to concatenate. 

Another error I met is as follow:
Traceback (most recent call last):
  File "prepare_data/collect_indoor3d_data.py", line 28, in <module>
    indoor3d_util.collect_point_label(anno_path, os.path.join(output_folder, out_filename), 'txt')
  File "D:\dgcnn.pytorch-V2\prepare_data\indoor3d_util.py", line 65, in collect_point_label
    fout = open(out_filename, 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\dgcnn.pytorchV2\\data/stanford_indoor3d\\Stanford3dDataset_v1.2_Aligned_Version\\Area_1_conferenceRoom_1.txt'

**Comment by howtoknowseg** [comment]
File "D:\dgcnn.pytorch-master\data.py", line 149, in load_data_semseg
    test_area_name = "Area_" + test_area
TypeError: can only concatenate str (not "NoneType") to str

I have set test_area = ‘1’ but when printing it output 'none' in the terminal

**Comment by antao97** [comment]
I think the path "D:\dgcnn.pytorchV2\data/stanford_indoor3d\Stanford3dDataset_v1.2_Aligned_Version\Area_1_conferenceRoom_1.txt" should be "D:\dgcnn.pytorchV2\data\stanford_indoor3d\Stanford3dDataset_v1.2_Aligned_Version\Area_1_conferenceRoom_1.txt"

**Comment by howtoknowseg** [comment]
Thanks a lot! I used '//' to replace all the'\', and finally generated .npy in the folder. These files are not in the correct directory, I need to move them manually. The previous error was due to the gen_indoor3d_h5.py not running correctly. 
What's more, pred = seg_pred.max(dim=2)[1](in main_semseg.py, line 111) leads to the following error： 
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)
I have noticed in the main_cls.py, the parameter is dim=1. Could you please explain the difference?

**Comment by howtoknowseg** [comment]
By the way, after the terminal outputs 'Let's use 1 GPUs! Use SGD', there is no new output for about two hours. Is this a normal phenomenon?

**Comment by antao97** [comment]
Please use the batch size `--batch_size` larger than 1.

**Comment by howtoknowseg** [comment]
Could you give me some information about the training time on the task of semseg with 1 GPUs and batch size is 32, for the full dataset?

**Comment by antao97** [comment]
Because I use 4 GPUs, I can't provide the training time for 1 GPU.

**Comment by howtoknowseg** [comment]
Could you tell me your training time for reference?Thanks in advance

**Comment by antao97** [comment]
I remember the time is less than one day.
