### ISSUE TITLE
Using this implementation with paris-lille or semantic3D (outdoor data)

### ISSUE THREAD

**Issue by shayannikoohemat** [AnTao97/dgcnn.pytorch#35]
How can we use this implementation with a different dataset such as paris-llile3D and semantic3D (outdoor data)? Do we need to use a modification of `gen_indoor3D_h5.py` is it possible to use a simple data structure like just tiles of data?

**Comment by antao97** [comment]
I think how to preprocess your dataset depends on your own. You can try the preprocessing style of S3DIS and modify it for your dataset.
