### ISSUE TITLE
about data augmentation

### ISSUE THREAD

**Issue by amiltonwong** [AnTao97/dgcnn.pytorch#37]
Hi, @AnTao97 ,

It seems that your code did not implement the data augmentation (e.g. random translation, random anisotropic scaling). With the augmentation appended, I think the result from your implementation will give much higher accuracy than the official one. Would you plan to append it?

Thanks~

**Comment by antao97** [comment]
I'm sorry that I haven't plan to do these data augmentations. If you apply these tricks and have performance improvement, please tell me about the details! You are welcomed to start a pull request on this repo. I will be happy to upgrade my code with you.
