### ISSUE TITLE
get_graph_feature函数返回的特征的问题

### ISSUE THREAD

**Issue by ch19971118** [AnTao97/dgcnn.pytorch#40]
您好，我是一个刚入门这个领域的小白。我在原文的公式（8）中看到作者给(xj-xi)和xi分别加了一个函数表示其权重，但是在您的代码中没有找到跟这个权重对应的地方，很困惑，希望您能告知一下是什么原因，万分感谢！

**Comment by antao97** [comment]
权重是需要学习的网络参数，在代码中用self.conv1(x)表示，self.conv1(x)定义中可以看到self.conv1(x)包含了nn.Conv2d、self.bn1和nn.LeakyReLU

**Comment by ch19971118** [comment]
> 权重是需要学习的网络参数，在代码中用self.conv1(x)表示，self.conv1(x)定义中可以看到self.conv1(x)包含了nn.Conv2d、self.bn1和nn.LeakyReLU

明白了，感谢大佬解惑！
