### ISSUE TITLE
训练语义分割时的问题

### ISSUE THREAD

**Issue by ch19971118** [AnTao97/dgcnn.pytorch#41]
您好！抱歉这么快就又来叨扰您了。
我想运行您的训练语义分割模型的代码，即python main_semseg.py --exp_name=semseg_6 --test_area=6 
在我执行这个代码之前，我已经下载了数据集Stanford3dDataset_v1.2_Aligned_Version.zip和数据集indoor3d_sem_seg_hdf5_data.zip。我根据提示在您的项目下创建了data/文件夹，然后将Stanford3dDataset_v1.2_Aligned_Version.zip放入其中，然后执行python main_semseg.py --exp_name=semseg_6 --test_area=6代码。但是执行完后并没有在data/目录下生成文件夹，在上级目录生成了Stanford3dDataset_v1.2_Aligned_Version文件夹。我将其放至data/文件夹中，并将indoor3d_sem_seg_hdf5_data.zip解压，然后也放到data/文件夹中，然后执行代码。在data/中得到了两个文件夹，一个是stanford_indoor3d文件夹，里面生成了一堆.npy文件，还得到了indoor3d_sem_seg_hdf5_data_test文件夹，里面有一个all_files.txt和一个room_filelist.txt，其中第一个txt是空的，第二个里面有很多类似Area_1_conferenceRoom_1这样的数据。代码运行到这里时就报错了，报错信息为
Namespace(batch_size=32, dataset='S3DIS', dropout=0.5, emb_dims=1024, epochs=100, eval=False, exp_name='semseg_6', k=20, lr=0.001, model='dgcnn', model_root='', momentum=0.9, no_cuda=False, num_points=4096, scheduler='cos', seed=1, test_area='6', test_batch_size=16, use_sgd=True)
Using GPU : 0 from 1 devices
Traceback (most recent call last):
  File "main_semseg.py", line 314, in <module>
    train(args, io)
  File "main_semseg.py", line 55, in train
    test_loader = DataLoader(S3DIS(partition='test', num_points=args.num_points, test_area=args.test_area), 
  File "/home/zpf/chenhao/dgcnn.pytorch-master/data.py", line 247, in __init__
    self.data, self.seg = load_data_semseg(partition, test_area)
  File "/home/zpf/chenhao/dgcnn.pytorch-master/data.py", line 148, in load_data_semseg
    data_batches = np.concatenate(data_batchlist, 0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
已经尝试了几次都是这样，不知道该怎么解决，是哪个步骤漏了还是怎么。希望您能告知，十分感谢！！

**Comment by antao97** [comment]
你把`indoor3d_sem_seg_hdf5_data_test`文件夹删了，重新运行一遍。

我刚刚更新了代码，这个bug已经改正了

**Comment by antao97** [comment]
现在的代码从0开始运行是没有问题的，不会出现上述bug了

**Comment by ch19971118** [comment]
好的，谢谢大佬！





------------------ 原始邮件 ------------------
发件人: An Tao ***@***.***&gt;
发送时间: 2021年4月19日 16:48
收件人: AnTao97/dgcnn.pytorch ***@***.***&gt;
抄送: ch19971118 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[AnTao97/dgcnn.pytorch] 训练语义分割时的问题 (#41)





 
现在的代码从0开始运行是没有问题的，不会出现上述bug了

**Comment by pompeii222** [comment]
请问，每次运行又会出现这个indoor3d_sem_seg_hdf5_data_test文件夹，删了重新运行还是报错是为什么

**Comment by antao97** [comment]
indoor3d_sem_seg_hdf5_data_test文件夹是必备的，你的问题似乎在于没有正确产生这个文件夹下的内容。相关bug我已经更新，请从新按照指示把手动下载的数据集放到data目录下，并正常运行一遍代码

**Comment by pompeii222** [comment]
您好，我重新clone您的项目，在您的项目下建立data/文件夹，并将手动下载的数据集Stanford3dDataset_v1.2_Aligned_Version.zip放入其中，还是出现一楼出现的问题。请问有什么步骤遗漏了吗，麻烦您了。

**Comment by antao97** [comment]
现在好了，重新clone一下，按照步骤运行

**Comment by pompeii222** [comment]
实在抱歉再次叨扰您，重新clone之后运行，得到indoor3d_sem_seg_hdf5_data_test文件夹，里面只有一个all_files.txt和一个room_filelist.txt，all_files.txt是空的，也并没有生成indoor3d_sem_seg_hdf5_data_test/ply_data_all_'+ str(i) +'.h5的文件，不知道是我步骤出现问题还是没有调用prepare_data/gen_indoor3d_h5.py成功。请问成功生成的indoor3d_sem_seg_hdf5_data_test文件夹应该是什么样的？

**Comment by antao97** [comment]
indoor3d_sem_seg_hdf5_data_test文件夹内容：
![截屏2021-05-19 下午8 50 38](https://user-images.githubusercontent.com/41320807/118815520-dffe3d00-b8e3-11eb-9965-d2216301e5be.png)

我今天已经测试过了代码，最新更新的是可以跑通的，应该是你的问题，没有成功调用prepare_data/gen_indoor3d_h5.py

**Comment by pompeii222** [comment]
好的，谢谢大佬！

**Comment by LZQ1204** [comment]
> 好的，谢谢大佬！
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: An Tao ***@***.***&gt; 发送时间: 2021年4月19日 16:48 收件人: AnTao97/dgcnn.pytorch ***@***.***&gt; 抄送: ch19971118 ***@***.***&gt;, Author ***@***.***&gt; 主题: 回复：[AnTao97/dgcnn.pytorch] 训练语义分割时的问题 (#41) 现在的代码从0开始运行是没有问题的，不会出现上述bug了 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

请问，您解决了吗，为什么我还是有错

**Comment by fukexue** [comment]
> > 好的，谢谢大佬！
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: An Tao _**@**_._**> 发送时间: 2021年4月19日 16:48 收件人: AnTao97/dgcnn.pytorch _**@**_.**_> 抄送: ch19971118 _**@**_._**>, Author _**@**_.**_> 主题: 回复：[AnTao97/dgcnn.pytorch] 训练语义分割时的问题 (#41) 现在的代码从0开始运行是没有问题的，不会出现上述bug了 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 请问，您解决了吗，为什么我还是有错

1、可以采用将h5py.File(h5_filename, mode='a')修改为h5py.File(h5_filename, mode='a')
2、可以给data文件夹施加权限chmod a+x data

**Comment by Hatsu1314Casper** [comment]
> > > 好的，谢谢大佬！
> > > […](#)
> > > ------------------ 原始邮件 ------------------ 发件人: An Tao _**@**_._**> 发送时间: 2021年4月19日 16:48 收件人: AnTao97/dgcnn.pytorch _**@**_.**_> 抄送: ch19971118 _**@**_._**>, Author _**@**_.**_> 主题: 回复：[AnTao97/dgcnn.pytorch] 训练语义分割时的问题 (#41) 现在的代码从0开始运行是没有问题的，不会出现上述bug了 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> > 
> > 
> > 请问，您解决了吗，为什么我还是有错
> 
> 1、可以采用将h5py.File(h5_filename, mode='a')修改为h5py.File(h5_filename, mode='a') 2、可以给data文件夹施加权限chmod a+x data

感谢您的建议！我在其他用到pointnet的点云处理网络中碰到了同样的问题，只需加一个mode='a'即可，感谢！
