### ISSUE TITLE
part segmentation visualization script

### ISSUE THREAD

**Issue by struggle2893** [AnTao97/dgcnn.pytorch#42]
Hi，
Thank you very much for sharing the code on DGCNN. I have completed the training on part segmentation and want to visualize it. I read your suggestions on #8 and #26. But I only exported points (x, y, z) and cannot assign the color (R,G,B ) by the label . Can you share your visualization  script? thank you very much!
I'm sorry to trouble you, and I'm sorry to ask you such a simple question, I am a beginner in point cloud work, I hope you understand, thank you very much.

**Comment by antao97** [comment]
I'm sorry that I didn't write a visualization script. 

Please tell me if you don't know the label of each point or don't know how to connect colors with labels.

**Comment by struggle2893** [comment]
I don't know how to connect colors with labels.

**Comment by antao97** [comment]
You can init a color list with 50 colors, where each color corresponds to a label.

See #10 for more details.

**Comment by struggle2893** [comment]
Thank you very much!

**Comment by LZQ1204** [comment]
> Thank you very much!



> I don't know how to connect colors with labels.



> Thank you very much!

Can you share your visualization script? thank you very much!

**Comment by LZQ1204** [comment]
> Thank you very much!

Can you share your visualization script? thank you very much!

**Comment by antao97** [comment]
The visualization code is added in this repo.
