### ISSUE TITLE
about part segmention visualization  script

### ISSUE THREAD

**Issue by struggle2893** [AnTao97/dgcnn.pytorch#43]
Hi，
Thank you very much for sharing the code on DGCNN. I have completed the training on part segmentation and want to visualize it. I read your suggestions on #8 and #26. But I only exported points (x, y, z) and cannot assign the color (R,G,B ) by the label . Can you share your visualization  script? thank you very much!
I'm sorry to trouble you, and I'm sorry to ask you such a simple question, I am a beginner in point cloud work, I hope you understand, thank you very much.

**Comment by antao97** [comment]
See #42

**Comment by antao97** [comment]
The visualization code is added in this repo.
