### ISSUE TITLE
Question about Edge Conv

### ISSUE THREAD

**Issue by edshkim98** [AnTao97/dgcnn.pytorch#44]
Hi, I have a question about Edge Conv implementation of yours.
EdgeConv constructs K number of local graph making the shape as Batch_size * C * Pts * K.
According to your implementation, kernel 1 * 1 is applied and it means that the local kernel weights are all same.
However, in image convolution, weights in each kernel is different.
For example, if there is 3 * 3 kernel conv, current dgcnn has same weight across the kernel.
Then, doesn't it make more sense to use (1 * K) like x-conv from PointCNN to capture local features?
What is your reason behind using 1 * 1 convolution rather than 1 * K convolution?
Thank you!

**Comment by antao97** [comment]
Suppose you want to transform features from (Batch_size, C1, Pts, K) to (Batch_size, C2, Pts, K). In convolution, the size of each `nn.Conv2d` kernel is (1, C1, 1, 1). There are C2 kernels. 

See https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html?highlight=nn%20conv2d#torch.nn.Conv2d for more details.

**Comment by edshkim98** [comment]
Thank you for the reply.
Maybe I am misunderstanding something, but so I know that there will be C2 different kernels as output features will be C2.
However, 1 * 1 kernel only extracts features from individual point like pointnet, so it can not extract any local features.
How does DGCNN achieve this by using 1 * 1 kernel? 
I presume it achieves it by calculating edge features and max-pool operation.
Is this correct?

**Comment by antao97** [comment]
There is a max-pooling after each convolution to aggregate local features.

**Comment by antao97** [comment]
I suggest you refer to the DGCNN paper on how DGCNN extracts local features. My code strictly follows the paper for implementation.
