### ISSUE TITLE
question about test on one class choice

### ISSUE THREAD

**Issue by MrAirplaneLu** [AnTao97/dgcnn.pytorch#45]
I directly train the full dataset, then use this trained model to test on one class choice
but there was a problem:
RuntimeError: Error(s) in loading state_dict for DataParallel:
size mismatch for module.conv11.weight: copying a param with shape torch.Size([50, 256, 1]) from checkpoint, the shape in current model is torch.Size([4, 128, 1]).

I hope you can answer. Thank you very much！

![image](https://user-images.githubusercontent.com/45754132/116500228-af2c7880-a8e0-11eb-87a8-43c49312ab24.png)

**Comment by antao97** [comment]
If your model is trained with the full dataset, you can't test it with a single class in the test set. 

If you really want to test its performance in one class, see #10.

**Comment by MrAirplaneLu** [comment]
Now I want to check the Miou, ACC and other information of each class. Is there any convenient way?
Thanks again

**Comment by antao97** [comment]
I think it may be impossible to use existing functions to calculate the mAcc and mIoU of a single class if your model is trained with full dataset. The label prediction of each point can be in anywhere of 50 labels. You can write some code to calculate them manually.

You can still calculate Acc by using `metrics.accuracy_score`.

**Comment by MrAirplaneLu** [comment]
Then I can calculate the Miou of each class separately in the prediction, which is equivalent to modifying the calculation_ shape_ IOU, right?

**Comment by antao97** [comment]
Yes

**Comment by MrAirplaneLu** [comment]
Thank you very much
