### ISSUE TITLE
question about gt

### ISSUE THREAD

**Issue by MrAirplaneLu** [AnTao97/dgcnn.pytorch#47]
Here, the label of the incoming network is just the type of point cloud. Why not import SEG to enhance the fitting effect of training?
![image](https://user-images.githubusercontent.com/45754132/117138634-e073df80-addd-11eb-9bd8-45403def6d10.png)

**Comment by antao97** [comment]
You can try it if you want.

**Comment by MrAirplaneLu** [comment]
Because I see many point cloud segmentation without SEG tag into the network, I have this doubt.
OK, I'll add in and try.
