### ISSUE TITLE
部分分割中对于每类物体单独测试精度的问题

### ISSUE THREAD

**Issue by ch19971118** [AnTao97/dgcnn.pytorch#50]
作者您好，我用跑出来的部分分割模型按照您的代码对每一类物体单独测试，出现了问题，我看到其他人也提出过这个问题，看到了您在#10里面的答复。
If you want to evaluate performance in a particular class with full dataset trained, the only thing you need to do is to calculate Acc and mIoU in some chosen dims of the 50-dim vector.
我根据您说的去修改calculate_shape_IoU这个函数，但是一直没成功，我不是很明白您在#10里面的答复。
您有时间时能详细跟我说说吗，万分感谢！

**Comment by antao97** [comment]
如果使用全部数据集训练，那么评估的时候对所有类别进行统一测试并取平均结果，即README中85.2的结果；如果使用单独类别训练，那么评估的时候对该类别进行测试得出该类别的结果，即README中各个类别的结果。如果使用全部数据集训练但是希望对单独的一个类进行评估，需要改写`calculate_shape_IoU`函数，从而使得达到对某一个类别单独测试的效果。

https://github.com/AnTao97/dgcnn.pytorch/issues/10 里面是讲了整个数据集里输出的50个part分别对应的是那些类别，因为一个类别中有几个part，总共有16个类别。

`self.cat2id`是16个类别分别对应的索引
`self.seg_num`是每个类别中part的数量
`self.index_start`是输出的50个part中各个类别的开始索引

例如`bag`，从`self.cat2id`可以知道对应的索引是1，从`self.seg_num`的索引1可以知道在`bag`有2个part，从`self.index_start`的索引1可以知道在`bag`在总共50个part中从索引4开始算。如果我要评估`bag`的Acc和mIoU，那么需要将评估范围从50个part（索引0-49）变成索引为4-5的2个part。

**Comment by ch19971118** [comment]
> 如果使用全部数据集训练，那么评估的时候对所有类别进行统一测试并取平均结果，即README中85.2的结果；如果使用单独类别训练，那么评估的时候对该类别进行测试得出该类别的结果，即README中各个类别的结果。如果使用全部数据集训练但是希望对单独的一个类进行评估，需要改写`calculate_shape_IoU`函数，从而使得达到对某一个类别单独测试的效果。
> 
> #10 里面是讲了整个数据集里输出的50个part分别对应的是那些类别，因为一个类别中有几个part，总共有16个类别。
> 
> `self.cat2id`是16个类别分别对应的索引
> `self.seg_num`是每个类别中part的数量
> `self.index_start`是输出的50个part中各个类别的开始索引
> 
> 例如`bag`，从`self.cat2id`可以知道对应的索引是1，从`self.seg_num`的索引1可以知道在`bag`有2个part，从`self.index_start`的索引1可以知道在`bag`在总共50个part中从索引4开始算。如果我要评估`bag`的Acc和mIoU，那么需要将评估范围从50个part（索引0-49）变成索引为4-5的2个part。



> 如果使用全部数据集训练，那么评估的时候对所有类别进行统一测试并取平均结果，即README中85.2的结果；如果使用单独类别训练，那么评估的时候对该类别进行测试得出该类别的结果，即README中各个类别的结果。如果使用全部数据集训练但是希望对单独的一个类进行评估，需要改写`calculate_shape_IoU`函数，从而使得达到对某一个类别单独测试的效果。
> 
> #10 里面是讲了整个数据集里输出的50个part分别对应的是那些类别，因为一个类别中有几个part，总共有16个类别。
> 
> `self.cat2id`是16个类别分别对应的索引
> `self.seg_num`是每个类别中part的数量
> `self.index_start`是输出的50个part中各个类别的开始索引
> 
> 例如`bag`，从`self.cat2id`可以知道对应的索引是1，从`self.seg_num`的索引1可以知道在`bag`有2个part，从`self.index_start`的索引1可以知道在`bag`在总共50个part中从索引4开始算。如果我要评估`bag`的Acc和mIoU，那么需要将评估范围从50个part（索引0-49）变成索引为4-5的2个part。

感谢陶博士您的细心解答！
恕我愚钝，我看了您的回答后我的理解是要测某一个类别单独mIOU就是将评估范围设置在该类别物体从它开始的下标直到经过该物体对应的part数这个范围之内，落实到`calculate_shape_IoU`函数中，我将`for part in parts:`中parts的范围设置成您说的bag对应的4-5，但是测试结果不正确。除了个地方以外我不知道该函数中该从哪里改起。。您能点拨一下吗

**Comment by antao97** [comment]
你指的测试结果不正确是无法复现README中`bag`的结果吗？我上面解释过了，正常来说，单独类别的测试结果是通过单独类别训练得到的，即如下代码对`bag`类别单独进行训练，与全部数据集训练不同的是加了`--class_choice=bag`，如果使用全部数据集训练则不需要加`--class_choice`。为了标记方便起见将`bag`类别训练的实验名称设置为`--exp_name=partseg_bag`中也带有`bag`。

```
python main_partseg.py --exp_name=partseg_bag --class_choice=bag
```

使用如下代码对上述训练得出的模型进行测试，即测试`bag`类别的结果

```
python main_partseg.py --exp_name=partseg_bag_eval --class_choice=bag --eval=True --model_path=checkpoints/partseg_bag/models/model.t7
```

**Comment by ch19971118** [comment]
> 你指的测试结果不正确是无法复现README中`bag`的结果吗？我上面解释过了，正常来说，单独类别的测试结果是通过单独类别训练得到的，即如下代码对`bag`类别单独进行训练，与全部数据集训练不同的是加了`--class_choice=bag`，如果使用全部数据集训练则不需要加`--class_choice`。为了标记方便起见将`bag`类别训练的实验名称设置为`--exp_name=partseg_bag`中也带有`bag`。
> 
> ```
> python main_partseg.py --exp_name=partseg_bag --class_choice=bag
> ```
> 
> 使用如下代码对上述训练得出的模型进行测试，即测试`bag`类别的结果
> 
> ```
> python main_partseg.py --exp_name=partseg_bag_eval --class_choice=bag --eval=True --model_path=checkpoints/partseg_bag/models/model.t7
> ```

我训练的模型是用全部训练集训练出的模型，我想用这个模型去单独测试每个类别的IOU。
我修改了`calculate_shape_IoU`函数中的parts，如下

            parts = range(4, 5)         ######4-5  bag对应的part

得到的结果是
Test :: test acc: 0.939085, test avg acc: 0.817044, test iou: 0.997693
得到这样一个IOU...
我想知道怎么修改`calculate_shape_IoU`函数才是正确的

想把那个函数完整地复制上来的。。但是在这上面编辑的结构很乱。。我只改了parts那一个地方

**Comment by antao97** [comment]
首先，这个单独类别的结果是供你自己调试代码使用的，不是需要汇报提交的结果，是一个内部参考的结果，代码细节可供写法有很多种，计算方式的细节也有很多种，因此我无法对你的个人需求进行指导。每个类别需要汇报的结果是单独类别训练后得到的，训练代码我上面讲过了。

其次，索引4-5的代码是`range(4,6)`，不是`range(4,5)`

**Comment by ch19971118** [comment]
> 首先，这个单独类别的结果是供你自己调试代码使用的，不是需要汇报提交的结果，是一个内部参考的结果，代码细节可供写法有很多种，计算方式的细节也有很多种，因此我无法对你的个人需求进行指导。每个类别需要汇报的结果是单独类别训练后得到的，训练代码我上面讲过了。
> 
> 其次，索引4-5的代码是`range(4,6)`，不是`range(4,5)`

明白了，我之前对单独测试的结果的来源理解有问题，感谢大佬百忙中给我解惑！
