### ISSUE TITLE
关于测试结果可视化问题

### ISSUE THREAD

**Issue by zeng-ziyin** [AnTao97/dgcnn.pytorch#54]
请问下您有测试结果可视化代码吗？就是那种论文中最后对比实验中的，点云分割结果可视化的代码。有的话万分感谢 @AnTao97

**Comment by zeng-ziyin** [comment]
想更直观的看到分割结果

**Comment by antao97** [comment]
没有

**Comment by antao97** [comment]
最新更新的代码包含了可视化代码

**Comment by zeng-ziyin** [comment]
太感谢了，我自己写的可视化代码运行速度非常慢，试试您这边的
万分感谢大佬的分享




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AnTao97/dgcnn.pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月20日(星期二) 晚上8:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AnTao97/dgcnn.pytorch] 关于测试结果可视化问题 (#54)





 
最新更新的代码包含了可视化代码
