### ISSUE TITLE
About the ShapeNet dataset

### ISSUE THREAD

**Issue by Yellowshuohahaha** [AnTao97/dgcnn.pytorch#56]
Hi, thanks for your great work! I want to ask what pointcloud, label, seg represent in ShapeNetPart dataset?

**Comment by Yellowshuohahaha** [comment]
And can we use the part segmentation code of dgcnn to perform instance segmentation with only one category? As shown in the figure below, I want to separate each part inside by training dgcnn.
![3c6bbb15d1f585cee755331306d31a2](https://user-images.githubusercontent.com/48409315/128842001-695a8b8e-2c7f-4236-a271-7175a139af9f.png)

**Comment by antao97** [comment]
> Hi, thanks for your great work! I want to ask what pointcloud, label, seg represent in ShapeNetPart dataset?

Please see DGCNN paper for details.

**Comment by antao97** [comment]
> And can we use the part segmentation code of dgcnn to perform instance segmentation with only one category? As shown in the figure below, I want to separate each part inside by training dgcnn.
> ![3c6bbb15d1f585cee755331306d31a2](https://user-images.githubusercontent.com/48409315/128842001-695a8b8e-2c7f-4236-a271-7175a139af9f.png)

DGCNN can't perform instance segmentation. You need to understand what the part segmentation task is.
