### ISSUE TITLE
About semseg Visualization

### ISSUE THREAD

**Issue by 964918993** [AnTao97/dgcnn.pytorch#57]
Sorry to bother you.

I followed the readme file and first ran a training and test without visual commants on main_semseg. 

Then, after running "python main_semseg.py --exp_name=semseg_eval_6 --test_area=6 --eval=True 
--model_root=outputs/semseg/models/ --visu=area_6_office_1 --visu_ format=ply", 

it prompts the error "OSError: data/indoor3d_sem_seg_hdf5_data_test/raw_data3d/Area_6/office_1(7007).txt not found."

I read the file "indoor3d_util.py" and learned that "/raw_data3d/Area_6/office_1(7007)" seems to be generated automatically during the data preprocessing, but the actual operation does not seem to be generated correctly.

Do you understand how to deal with this problem?

Thanks!

**Comment by antao97** [comment]
I retest my code and find no error. It seems that you have problem in `np.savetxt`, or you once interrupted the data preprocessing. You can delete `data/indoor3d_sem_seg_hdf5_data` and `data/indoor3d_sem_seg_hdf5_data_test` and follow README to rerun a testing task and a visualization task.
