### ISSUE TITLE
redundancy in indoor3d_sem_seg_hdf5_data_test 

### ISSUE THREAD

**Issue by hansen7** [AnTao97/dgcnn.pytorch#6]
Hi @AnTao97, thanks for your sharing!

For the semantic segmentation parts, maybe `indoor3d_sem_seg_hdf5_data_test` is a bit redundant, right? 
Since
https://github.com/AnTao97/dgcnn.pytorch/blob/c2da60252eb84c634650f7ab2535fc1fcab67451/data.py#L156-L162

**Comment by antao97** [comment]
The main difference between training and testing set is that each block in training set overlaps with its neighbor blocks in 0.5m, i.e. all blocks in a given room are cropped with stride=0.5m, while all blocks in testing set are not overlap with others. 

The data in https://shapenet.cs.stanford.edu/media/indoor3d_sem_seg_hdf5_data.zip is only for training set, not testing set. You are required to generate testing data `data/indoor3d_sem_seg_hdf5_data_test/` from original S3DIS dataset `Stanford3dDataset_v1.2_Aligned_Version.zip`. This data generation will be done when you run training script `main_semseg.py` the first time with `Stanford3dDataset_v1.2_Aligned_Version.zip` downloaded.

See #1 for more details.

**Comment by hansen7** [comment]
Oh, thanks for clarification, w.r.t #1 , actually I also think that the original implementation does not test on whole point set :)
