### ISSUE TITLE
语义分割方面的问题

### ISSUE THREAD

**Issue by atomishcv** [AnTao97/dgcnn.pytorch#60]
你好，我在运行语义分割训练的部分时，发现训练集和验证集的精度没有发生太大的变化。
Train 16, loss: nan, train acc: 0.255400, train avg acc: 0.076923, train iou: 0.019646
Test 16, loss: nan, test acc: 0.199915, test avg acc: 0.076923, test iou: 0.015378
Train 17, loss: nan, train acc: 0.255371, train avg acc: 0.076923, train iou: 0.019644
Test 17, loss: nan, test acc: 0.199915, test avg acc: 0.076923, test iou: 0.015378
Train 18, loss: nan, train acc: 0.255389, train avg acc: 0.076923, train iou: 0.019645
Test 18, loss: nan, test acc: 0.199915, test avg acc: 0.076923, test iou: 0.015378

**Comment by antao97** [comment]
你跑完程序了吗？还是这样？

**Comment by atomishcv** [comment]
好的，我先跑完整个程序，谢谢大佬
