### ISSUE TITLE
the relationship between indoor3d_sem_seg_hdf5_data_test and indoor3d_sem_seg_hdf5_data？

### ISSUE THREAD

**Issue by swzaaaaaaa** [AnTao97/dgcnn.pytorch#61]
Excuse me, the relationship between indoor3d_sem_seg_hdf5_data_test and indoor3d_sem_seg_hdf5_data？

**Comment by antao97** [comment]
`indoor3d_sem_seg_hdf5_data_test` is for testing set, and `indoor3d_sem_seg_hdf5_data` is for training set.

**Comment by swzaaaaaaa** [comment]
请问，这俩都是完整的数据集吗，那怎么区分测试的时候在指定area测试？

**Comment by antao97** [comment]
See https://github.com/AnTao97/dgcnn.pytorch/issues/6

**Comment by swzaaaaaaa** [comment]
好的，感谢，明白了
