### ISSUE TITLE
May I ask, what is the MIOU of S3DIS dataset in  Area-5？

### ISSUE THREAD

**Issue by swzaaaaaaa** [AnTao97/dgcnn.pytorch#62]
May I ask, what is the MIOU of S3DIS dataset in  Area-5？My own test was 49%, which feels a little low？

**Comment by antao97** [comment]
See https://github.com/AnTao97/dgcnn.pytorch/issues/20

**Comment by swzaaaaaaa** [comment]
Thanks.
