### ISSUE TITLE
测试

### ISSUE THREAD

**Issue by LZQ1204** [AnTao97/dgcnn.pytorch#63]
您好，打扰您了，我看了一些关于三维深度学习方面的网络，现有有一个问题：三维深度学习网络是否可以像二维深度学习网络那样，通过训练好的模型，对于输入的一张类似数据集的图片进行分类分割检测等任务，因为我发现我看过的三维深度学习网络都没有对某一个点云数据进行测试和可视化的？

**Comment by antao97** [comment]
我没有看懂你的问题，建议你多了解深度学习的工作后，再提问
