### ISSUE TITLE
Help with data being of length 9 in second dimension during semantic segmentation

### ISSUE THREAD

**Issue by GastonMazzei** [AnTao97/dgcnn.pytorch#64]
Hi ^.^ 
I open this issue to ask about the data consumed by the semantic segmentation model having length 9 in its second dimension.
I understand there is a transform involved in the first layer, but more precisely:

We've got a bunch of "data" elements (collected during [this](https://github.com/AnTao97/dgcnn.pytorch/blob/master/main_semseg.py#L316) loop) and their corresponding segmentation class. 

We would like to get the original XYZ position from them. Is this possible?
Is my best guess "x,y,z are the first three elements of Data" correct? 😊
i.e.
`data.shape == (batch_size, 9, number_of_points)`
so to get one point it's
`x,y,z = data[0, :3, 0]`
and the rest are
`other_features = data[0,3:, 0]`

Quick reminder:
[Here](https://github.com/AnTao97/dgcnn.pytorch/blob/master/main_semseg.py#L295) the test_loader is initialized, and [here](https://github.com/AnTao97/dgcnn.pytorch/blob/master/main_semseg.py#L316) it's used to iterate.

Thanks, 
Gaston.

**Comment by antao97** [comment]
Correct

**Comment by GastonMazzei** [comment]
Thanks 😃 I'm looking at the `.h5` files and still failing to understand what the extra 6 entries are.

Are they `(x,y,z),(x,y,z),(x,y,z)` the coordinates of the three vertex of a triangular mesh? 

Concerning this repo: is there a function that can be used to convert point cloud sections in `x,y,z` format (i.e. numpy arrays of shape `(1,4096,3)` into the input format required by the net? Thanks.



Thank you for your help, I'll wait some time in case you find time to answer this last question and in any case close the issue as you have already answered my request.

**Comment by antao97** [comment]
See https://github.com/AnTao97/dgcnn.pytorch/issues/46
