### ISSUE TITLE
The visualization of scannet

### ISSUE THREAD

**Issue by zwy1996** [AnTao97/dgcnn.pytorch#68]
Hi，
Thanks for your help about the visualization  of point cloud. When I used the meshlab software to show the results of scannet with ply type, I met the following question

![微信截图_20220318173205](https://user-images.githubusercontent.com/39028963/158979783-e1427e7a-8529-4fd7-a4e2-316c8db176ef.png)
![微信截图_20220318173216](https://user-images.githubusercontent.com/39028963/158979844-9afb9687-ee58-4cae-9c24-12269527644c.png)
![微信截图_20220318173254](https://user-images.githubusercontent.com/39028963/158979900-36b4addc-bae7-45b8-800c-104522e25224.png)

![微信截图_20220318173244](https://user-images.githubusercontent.com/39028963/158979957-4b8d7c9f-50b1-4256-a485-a910cceaed67.png)

You can see the gt results is more light than the predicted results, Could you please tell me some advice about the difference about visualization 

Thank you very much!

**Comment by antao97** [comment]
This is because of the `alpha` channel. You need to set the value at 255. 

```
import numpy as np
from plyfile import PlyData

# Load PLY file
plydata = PlyData.read(os.path.join(YOUR_DARA_PATH, YOUR_ROOM_NAME, YOUR_ROOM_NAME+'_vh_clean_2.ply'))

# Set alpha channel
plydata.elements[0].data['alpha'] = 255

# Change the color according your predicted labels
rgb = np.array([list(YOUR_COLOR_LIST[p]) for p in YOUR_PREDICTION])
plydata.elements[0].data['red'] = rgb[:, 0]
plydata.elements[0].data['green'] = rgb[:, 1]
plydata.elements[0].data['blue'] = rgb[:, 2]

# Save PLY file
plydata.write('YOUR_SAVE_NAME.ply')
```

**Comment by zwy1996** [comment]
OK， I have tried this method. But I still met the difference.

Thank you very much!

**Comment by antao97** [comment]
I think you only write the point cloud in your PLY file, not the mesh.
