### ISSUE TITLE
Semantic Segmentation S3DIS label annotations

### ISSUE THREAD

**Issue by Shaurya-47** [AnTao97/dgcnn.pytorch#69]
Hi. Thanks a lot for the visualization code for Semantic Segmentation on S3DIS. However, I am unable to find the annotations for the 13 categories/labels anywhere in this repository or even the original S3DIS documentation. What I mean by that is what the labels stand for: eg. 0 is floor, 1 is chair, etc. It would be really helpful if you could point me to where I can find that information. 

Thank you!

**Comment by antao97** [comment]
See https://github.com/AnTao97/dgcnn.pytorch/blob/master/prepare_data/meta/semseg_colors.txt

**Comment by Shaurya-47** [comment]
Thanks a lot! Sorry for not noticing these files earlier. I am closing this issue.
