### ISSUE TITLE
CLS Model

### ISSUE THREAD

**Issue by hansen7** [AnTao97/dgcnn.pytorch#7]
Hi @AnTao97 

Just want to double check, the classification model and training scripts are identical to the Yue's original branch, right?
I've checked and find no differences.

**Comment by antao97** [comment]
Yes~

The secret of performance improvement is merely to rerun the training script for more than one time and select the best model.

**Comment by hansen7** [comment]
Thanks, yeah.. I have to run many times to reproduce the reported numbers :)
