### ISSUE TITLE
Meshlab

### ISSUE THREAD

**Issue by csgogo** [AnTao97/dgcnn.pytorch#70]
Hi, An Tao. Thanks to you for providing the code.  Do you know how to export HD images in MeshLab (as shown in the paper)? All I can find is the screenshot button.

**Comment by antao97** [comment]
Sorry, I don't know. I use the screenshot button too.

**Comment by csgogo** [comment]
Hello, AnTao!
&nbsp; &nbsp; I am wondering if you made a mistake in writing algorithmic operations in one of your papers "SegGroup". In Algorithm 1 Node Clustering, the 6th step should be Cp=Cq, right?






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AnTao97/dgcnn.pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月1日(星期天) 上午9:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AnTao97/dgcnn.pytorch] Meshlab (Issue #70)





 
Closed #70.

**Comment by antao97** [comment]
@csgogo Yes, it is a mistake. Recently we will update our paper in arxiv.
