### ISSUE TITLE
S3DIS可视化中的一个小疑问

### ISSUE THREAD

**Issue by sunxr99** [AnTao97/dgcnn.pytorch#71]
`  data = np.loadtxt('data/indoor3d_sem_seg_hdf5_data_test/raw_data3d/Area_'+test_area+'/'+roomname+'('+str(visual_file_index)+').txt')`
您好，请问可视化代码中这一句读取的这个roomname(visual_file_index).txt文件是什么呢？原始数据集进行数据处理后不存在/raw_data3d/这个目录吧？是把未处理的数据集中的.txt放过去吗？

**Comment by antao97** [comment]
因为S3DIS数据集在处理的时候按1m乘1m的块处理（参考 #1），但是当可视化的时候需要可视化出来整个房间的点云，因此需要先把各个块的结果临时保存下来到`raw_data3d/`目录，当一个房间内所有块全部处理完成后，统一再加载这些临时保存下来的结果，整合输出整个房间的结果。

**Comment by sunxr99** [comment]
明白了，十分感谢您的回答。

**Comment by xiaoyangyang123** [comment]
> ` data = np.loadtxt('data/indoor3d_sem_seg_hdf5_data_test/raw_data3d/Area_'+test_area+'/'+roomname+'('+str(visual_file_index)+').txt')` 您好，请问可视化代码中这一句读取的这个roomname(visual_file_index).txt文件是什么呢？原始数据集进行数据处理后不存在/raw_data3d/这个目录吧？是把未处理的数据集中的.txt放过去吗？

你好，请问你您最后怎么解决的呢？
