### ISSUE TITLE
如何使用txt文本

### ISSUE THREAD

**Issue by Hambuger516** [AnTao97/dgcnn.pytorch#72]
Hi, An Tao. Thanks to you for providing the code. I want to use the .txt format，but i don't know how to make the shapenet‘s txt into the .h5. And also, do you have the code about the txt format. Thank you ~

**Comment by antao97** [comment]
For example, you now have a point cloud matrix `data` (N \times 3), a label vector `label` (N \times 1), and a segmentation mask vector `seg` (N \times 1). All these data are in NumPy format. You can use `data = numpy.loadtxt('data.txt')` to load your `.txt` file into NumPy data.

Then you can obtain your `.h5` data with the following code:
```
import h5py

f = h5py.File('dataset.h5', 'w')     
f['data'] = data
f['label'] = label
f['seg'] = seg
f.close() 
```

**Comment by Hambuger516** [comment]
> For example, you now have a point cloud matrix `data` (N \times 3), a label vector `label` (N \times 1), and a segmentation mask vector `seg` (N \times 1). All these data are in NumPy format. You can use `data = numpy.loadtxt('data.txt')` to load your `.txt` file into NumPy data.
> 
> Then you can obtain your `.h5` data with the following code:
> 
> ```
> import h5py
> 
> f = h5py.File('dataset.h5', 'w')     
> f['data'] = data
> f['label'] = label
> f['seg'] = seg
> f.close() 
> ```

**Comment by Hambuger516** [comment]
> For example, you now have a point cloud matrix `data` (N \times 3), a label vector `label` (N \times 1), and a segmentation mask vector `seg` (N \times 1). All these data are in NumPy format. You can use `data = numpy.loadtxt('data.txt')` to load your `.txt` file into NumPy data.
> 
> Then you can obtain your `.h5` data with the following code:
> 
> ```
> import h5py
> 
> f = h5py.File('dataset.h5', 'w')     
> f['data'] = data
> f['label'] = label
> f['seg'] = seg
> f.close() 
> ```
Thank you very much
