### ISSUE TITLE
代码运行结果，比原来的要高很多

### ISSUE THREAD

**Issue by JustDoItY** [AnTao97/dgcnn.pytorch#76]
这是我云行20轮，产生的test结果
<img width="729" alt="image" src="https://user-images.githubusercontent.com/35087665/187676613-83848047-b9a3-4093-8e09-3ddfa6bfe996.png">

这是我用的代码中pretrained的权重跑的。
<img width="709" alt="image" src="https://user-images.githubusercontent.com/35087665/187676778-04b9f932-c222-4eef-88ae-e8482b9d00a2.png">

这比原论文结果相差太多了吧。是我理解错了吗。

**Comment by JustDoItY** [comment]
你可以看我fork的代码，在outputs中有结果

**Comment by antao97** [comment]
我默认的batch size是32，使用了4张2080卡，你的batch size是10，只用了一张卡

**Comment by antao97** [comment]
以及默认的epoch是100，你只运行了20

**Comment by JustDoItY** [comment]
![image](https://user-images.githubusercontent.com/35087665/188396741-1618123f-e064-4da5-a464-9364f1385b20.png)
我的意思是精确度太高了吧。一张卡和小batch_size，不应该是精确度下降吗

**Comment by antao97** [comment]
根据你的log结果，你的结果比我pretrained的权重要差，我上面说了一些原因，比如只用了一张卡和小batch_size。

至于我使用我的代码训练出来的模型，即给出的pretrained的权重，能够复现出来比原文更好的结果，其实是挺意外的，我严格按照原来作者的tensorflow版本写的模型，只是训练方式上不太一样，我用了CosineAnnealingLR优化器，具体使用的batch_size、iteration和learning rate和原代码也可能有所不同。

**Comment by JustDoItY** [comment]
哥们，能帮我看一看吗，我这真是不知道怎么回事了。我给你邮件我的qq，注意看一下。麻烦帮帮忙，感谢。

**Comment by chenjt66a** [comment]
我保持默认设置，用了2张卡，batch size = 32, epochs = 100, test area 6 的 test acc = 0.895159, test avg acc = 0.815347, test iou = 0.717584, 感觉训练结果也挺高的。
