### ISSUE TITLE
Hello, I would like to ask, how do you test the miou of each class_names in the semantic segmentation content?

### ISSUE THREAD

**Issue by xiaoyangyang123** [AnTao97/dgcnn.pytorch#77]
Hello, I would like to ask, how do you test the miou of each class_names in the semantic segmentation content?

**Comment by antao97** [comment]
After all rooms have been tested, we collect the predictions of points in all rooms and evaluate the mIoU between the predictions and their ground-truth labels by `calculate_sem_IoU` function.
https://github.com/antao97/dgcnn.pytorch/blob/97785863ff7a82da8e2abe0945cf8d12c9cc6c18/main_semseg.py#L47-L61

**Comment by xiaoyangyang123** [comment]
Then if I want to follow
ceiling
floor
wall
beam
column
window
door
table
chair
sofa
bookcase
board
clutter
way to output its iou, how should it be applied?

**Comment by antao97** [comment]
print `all_ious`
https://github.com/antao97/dgcnn.pytorch/blob/97785863ff7a82da8e2abe0945cf8d12c9cc6c18/main_semseg.py#L358

**Comment by xiaoyangyang123** [comment]
ok thank you i'll try it
