### ISSUE TITLE
请问model的get_graph_feature中这一段代码是不是没有什么作用

### ISSUE THREAD

**Issue by JJBUP** [AnTao97/dgcnn.pytorch#78]
def get_graph_feature(x, k=20, idx=None, dim9=False):
    batch_size = x.size(0)
    num_points = x.size(2)
    x = x.view(batch_size, -1, num_points)
....

**Comment by antao97** [comment]
在目前的网络代码中的确没有什么用，这段代码的本意是如果x存在第3维feature，则统统归并到第1维。

**Comment by JJBUP** [comment]
感谢感谢
