### ISSUE TITLE
problems about transfer learning 

### ISSUE THREAD

**Issue by SkySeWker** [AnTao97/dgcnn.pytorch#82]
非常感谢您的工作，针对part seg部分，阅读完main_partseg.py及说明文件，我并没有发现可以使用已训练好的模型.pth\.t7来迁移学习训练新的数据集的相关代码段落，请问是这样吗？还是我疏忽没发现？
另外如果真的没有这部分代码，请问我想加上这个功能，可否提供参考代码、及需要修改的参数
感谢

**Comment by antao97** [comment]
这份代码只提供对于shapenetpart数据集的训练，没有迁移模块
你可以根据训练脚本自行修改数据加载部分

**Comment by SkySeWker** [comment]
您好，我在把自己的数据转换成.h5文件时有些疑问：
shapenet_partseg数据集由原来的txt文件转为.h5文件选2048个点的逻辑是什么？
主要就是hdf5['data'] shape:（N,2048,3）,这里的2048个点是怎么取的呢？是直接从每个txt文件中随机取2048个点保存，还是怎么取的

**Comment by antao97** [comment]
用最远点采样（Farthest Point Sampling）

**Comment by SkySeWker** [comment]
明白了感谢
