### ISSUE TITLE
Stanford shapenet site certificate expired

### ISSUE THREAD

**Issue by mflaxman10** [AnTao97/dgcnn.pytorch#9]
--2020-08-01 13:22:41--  https://shapenet.cs.stanford.edu/media/shapenet_part_seg_hdf5_data.zip
Resolving shapenet.cs.stanford.edu (shapenet.cs.stanford.edu)... 171.67.77.19
Connecting to shapenet.cs.stanford.edu (shapenet.cs.stanford.edu)|171.67.77.19|:443... connected.
ERROR: cannot verify shapenet.cs.stanford.edu's certificate, issued by ‘/C=US/ST=MI/L=Ann Arbor/O=Internet2/OU=InCommon/CN=InCommon RSA Server CA’:
  Issued certificate has expired.
To connect to shapenet.cs.stanford.edu insecurely, use `--no-check-certificate'.

**Comment by mflaxman10** [comment]
Workaround for now:

edited data.py wget statements to add --no-check-certificate flag:

os.system('wget %s --no-check-certificate; unzip %s' % (www, zipfile))

**Comment by antao97** [comment]
Thanks for your feedback! 

The revised version is updated.
